### ISSUE TITLE
AttributeError: module 'spartan.model' has no attribute 'SpecgreedyCubeFlowPlus'

### ISSUE THREAD

**Issue by hzlllll** [BGT-M/spartan2#49]
When  I install spartan2 by pip and try to import spartan, it throws the error AttributeError: module 'spartan.model' has no attribute 'SpecgreedyCubeFlowPlus'
![image](https://user-images.githubusercontent.com/38622091/144743998-6cdf29c0-3933-46ed-aedc-c15ee2ceb0d6.png)

**Comment by tdingquan** [comment]
This problem will be solved and published in version 0.1.3-post2.

**Comment by hzlllll** [comment]
> This problem will be solved and published in version 0.1.3-post2.

thx！
